USE LIBRARY_MANAGEMENT_DB;

DELIMITER $$

 CREATE DEFINER=`root`@`localhost` procedure SP_ADMIN_LOGIN (in A_user_name varchar(30) , in A_pass_word varchar(30) , out results bool )
begin 
select exists (
select * from admin_login
 where A_user_name = USER_NAME and A_pass_word = pass_word
)
into results;
END$$

CREATE PROCEDURE SP_GET_MEMBER_DETAILS()
BEGIN 
SELECT * FROM members;
END $$

CREATE PROCEDURE SP_MEMBER_REGISTER(
 IN USER_NAME VARCHAR(30) ,
 IN PASS_WORD VARCHAR(30) ,
 IN MEMBER_NAME VARCHAR(30),
 IN FATHER_NAME VARCHAR(30) ,
 IN GENDER VARCHAR(20) ,
 IN ADDRESS VARCHAR(30),
 IN PHONE_NUMBER INT,
 IN EMAIL VARCHAR(30) 
 )
 begin
 INSERT INTO memberS (  USER_NAME ,PASS_WORD ,MEMBER_NAME ,FATHER_NAME, GENDER,ADDRESS,PHONE_NUMBER ,EMAIL )
 VALUES (  USER_NAME ,PASS_WORD ,MEMBER_NAME ,FATHER_NAME, GENDER,ADDRESS,PHONE_NUMBER ,EMAIL );
 END  $$
 
 CREATE PROCEDURE SP_MEMBER_LOGIN (IN M_USER_NAME VARCHAR(30), IN M_PASS_WORD VARCHAR(30) , OUT RESULTS BOOL)
BEGIN 
SELECT EXISTS (
SELECT * FROM members
WHERE M_USER_NAME = USER_NAME AND M_PASS_WORD = pass_word
)
INTO RESULTS;
 END $$
 
 CREATE PROCEDURE SP_GET_BOOKS_DETAILS()
 BEGIN 
 SELECT * FROM BOOKS;
 END $$
 
 CREATE PROCEDURE ADD_NEW_BOOKS (IN  title VARCHAR(50), IN author VARCHAR(40), IN isbn INT ,IN  publisher VARCHAR(50), IN edition INT,IN  YEAR_OF_PUBLISHING INT)
 BEGIN 
 INSERT INTO BOOKS (title, author, isbn, publisher, edition, YEAR_OF_PUBLISHING) VALUES  (title, author, isbn, publisher, edition, YEAR_OF_PUBLISHING);
 END $$ 

create procedure SP_DELETE_BOOKS(IN B_ID INT )
BEGIN 
DELETE FROM BOOKS WHERE ID = B_ID;
END $$

CREATE PROCEDURE SP_DELETE_MEMBER(IN M_MEMBER_ID INT)
BEGIN 
DELETE FROM MEMBERS WHERE M_MEMBER_ID = MEMBER_ID;
END$$

CREATE PROCEDURE SP_UPDATE_BOOK (IN B_ID INT , IN  title VARCHAR(50), IN author VARCHAR(40),
 IN isbn INT ,IN  publisher VARCHAR(50), IN edition INT,IN YEAR_OF_PUBLISHING INT)
BEGIN
UPDATE BOOKS SET title = TITLE , author = AUTHOR , isbn= ISBN , publisher = PUBLISHER ,
YEAR_OF_PUBLISHING = YEAR_OF_PUBLISHING WHERE B_ID = ID;
END $$

CREATE PROCEDURE SP_CHECK_ISSUANCE ()
BEGIN 
SELECT * FROM issuance_details;
END $$


CREATE PROCEDURE SP_SEARCH_BOOKS (IN B_TITLE VARCHAR(50))
BEGIN 
SELECT * FROM BOOKS WHERE TITLE = B_TITLE ;
END $$

CREATE PROCEDURE SP_DELETE_ISSUANCE (IN I_ID INT)
BEGIN 
DELETE FROM ISSUANCE WHERE ISSUANCE_ID = I_ID;
END $$
