USE LIBRARY_MANAGEMENT_DB;
    
    CREATE OR REPLACE VIEW ISSUANCE_DETAILS AS 
    SELECT MEMBER_NAME , TITLE , ISSUE_DATE , DUE_DATE FROM ISSUANCE AS I 
    JOIN MEMBERS AS M ON I.MEMBER_ID = M.MEMBER_ID 
    JOIN BOOKS AS B ON B.ID = I.ID;
    
